apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: ingress-system
  labels:
    app: traefik

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: traefik
  namespace: ingress-system
  labels:
    app: traefik

spec:
  # replicas: 3
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      hostNetwork: true
      volumes:
        - name: traefik-conf
          configMap:
            name: traefik-configfile
      nodeSelector:
        pcgroup/edgenode: "true"
      containers:
        - name: traefik
          image: harbor.inm.com/docker.io/library/traefik:v2.6
          args:
            - --configfile=/etc/traefik/traefik.yaml
          ports:
            - name: web
              containerPort: 80
              hostPort: 80
            - name: websecure
              containerPort: 443
              hostPort: 443
            - name: api
              containerPort: 8080
              hostPort: 8080
          volumeMounts:
            - name: traefik-conf
              mountPath: /etc/traefik
              readOnly: true

---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: ingress-system
  labels:
    app: traefik
spec:
  # type: NodePort
  selector:
    app: traefik
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: web
      # nodePort: 31080
    - protocol: TCP
      port: 443
      name: https
      targetPort: websecure
      # nodePort: 31443
    - protocol: TCP
      port: 8080
      name: dashboard
      targetPort: api
      # nodePort: 31880
